<?php
$texts = array(
	'Mi cuenta' => 'My account',
	'Cerrar sesion' => 'Logout',
	'Tu cesta' => 'Your cart',
	'Comprar' => 'Checkout',
	'Entrar' => 'Login',
	'Mujer' => 'Woman',
	'MAS VENDIDO' => 'TOP SELLER',
	'Primavera-Verano' => 'Mid season sale',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Tu cesta' => 'Your cart',
	'Contacto' => 'Contact'
);
?>
